name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          sourcemod_version: 1.10-dev
          sdk: l4d2
          cc: clang
          cxx: clang++

        - os: windows-latest
          sourcemod_version: 1.10-dev
          sdk: l4d2
          cc: ""
          cxx: ""
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: 'src'
        
      - name: download ${{ matrix.sdk }} sdk
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: ${{ matrix.sdk }}
          path: hl2sdk-${{ matrix.sdk }}
        
      - name: download sourcemod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sourcemod_version }}
          path: 'sourcemod'
        
      - name: download sourcemod submodules
        run: |
          cd sourcemod
          git submodule update --init --recursive
        
      - name: download metamod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: 1.11-dev
          path: 'mmsource-1.11'
        
      - name: download ambuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: 'ambuild'
        
      - name: install ambuild
        if: runner.os == 'Windows'
        run: |
          cd ambuild
          python setup.py install
        
      - name: install ambuild
        if: runner.os == 'Linux'
        run: |
          cd ambuild
          sudo python setup.py install
          
      - name: install linux packages
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y --no-install-recommends gcc-multilib g++-multilib
        
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: x86

      - name: set cc and cxx variables
        if: runner.os == 'Linux'
        uses: allenevans/set-env@v2.0.0
        with:
          CC: clang
          CXX: clang++

      - name: configure ambuild
        run: |
          cd src
          mkdir build
          cd build
          python ../configure.py --sdks ${{ matrix.sdk }} --mms-path ../../mmsource-1.11
              
      - name: build
        run: |
          cd src/build
          ambuild

      - name: upload extension artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}_${{ github.sha }}
          path: src/build/package/
